[[plugins]]
repo     = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" タブの切り替え
nmap <C-p> <Plug>AirlineSelectPrevTab
nmap <C-n> <Plug>AirlineSelectNextTab

let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tagbar#enabled = 1
let g:airline_skip_empty_sections = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme = 'deus'
'''

[[plugins]]
repo = 'mhinz/vim-startify'
depends = 'vim-devicons'
hook_add = '''
let g:startify_files_number = 5
let g:startify_list_order = [
        \ ['♻  最近使ったファイル:'],
        \ 'files',
        \ ['♲  最近使ったファイル(カレントディレクトリ下):'],
        \ 'dir',
        \ ['⚑  セッション:'],
        \ 'sessions',
        \ ['☺  ブックマーク:'],
        \ 'bookmarks',
        \ ]
let g:startify_bookmarks = ["~/dotfiles/neovim/init.vim", "~/.gvimrc"]

" ASCII ARTを真ん中寄せする
" :h startifyを参照
function! s:filter_header(lines) abort
    let longest_line   = max(map(copy(a:lines), 'len(v:val)'))
    let centered_lines = map(copy(a:lines),
        \ 'repeat(" ", (&columns / 2) - (longest_line / 2)) . v:val')
    return centered_lines
	let g:startify_custom_header = s:filter_header(startify#fortune#cowsay())
endfunction
'''



# -------------------------
# COLORSCHEME
# -------------------------
[[plugins]]
repo = 'danilo-augusto/vim-afterglow'
hook_add = '''
    set termguicolors
    colorscheme afterglow
    set background=dark
    au ColorScheme * hi Normal ctermbg=none guibg=none
'''

[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
" important!!
set termguicolors
" for dark version
set background=dark

" for light version
" set background=light

" the configuration options should be placed before `colorscheme edge`
let g:edge_style = 'neon'
let g:edge_disable_italic_comment = 1

"colorscheme edge
'''

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'ujihisa/unite-colorscheme'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
  " set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  " au MyAutoCmd VimEnter * nested colorscheme hybrid
 au ColorScheme * hi Normal ctermbg=none guibg=none
'''
