# --------------------------------
# LSP (Language Server Protocol)
# --------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_add = '''
source ~/dotfiles/neovim/rc/hooks/coc.vim
'''

# --------------------------------
# プログラムの非同期実行
# --------------------------------
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/dotfiles/neovim/rc/hooks/quickrun.vim
'''


[[plugins]]
repo = 'Shougo/defx.nvim'


# -------------------------
# GIT
# -------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
" GitGutter styling to use · instead of +/-
let g:gitgutter_sign_added = '＋ '
let g:gitgutter_sign_modified = '» '
let g:gitgutter_sign_removed = '－ '
let g:gitgutter_sign_modified_removed = '« '
nmap ]g :GitGutterNextHunk<CR>
nmap [g :GitGutterPrevHunk<CR>
augroup VimDiff
  autocmd!
  autocmd VimEnter,FilterWritePre * if &diff | GitGutterDisable | endif
augroup END
'''


[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
nmap j <Plug>(accelerated_jk_gj)
nmap k <Plug>(accelerated_jk_gk)
'''

