


# ---------------------
# PYTHON
# ---------------------
[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python','py']
hook_add = '''
"" jedi-vim
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#popup_select_first = 0
let g:jedi#popup_on_dot = 0
let g:jedi#goto_assignments_command = "<leader>assign"
let g:jedi#goto_definitions_command = "<leader>def"
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>usage"
let g:jedi#rename_command = "<leader>rename"
let g:jedi#show_call_signatures = "0"
let g:jedi#completions_command = "<C-Space>"
let g:jedi#smart_auto_mappings = 0
let g:jedi#force_py_version = 3
autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python', 'py']

[[plugins]]
repo = 'raimon49/requirements.txt.vim'
on_ft = 'requirements'

[[plugins]]
repo = 'psf/black'
on_ft = ['python', 'py']



# ---------------------
# markdown
# ---------------------
[[plugins]]
# syntax highlight, auto-indent
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown', 'mkd']

[[plugins]]
# preview
# 【:MarkdownPreview】preview on
# 【:MarkdownPreviewStop】preview off
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'mkd']
build = 'cd app & yarn install'


[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = ['markdown', 'mkd']

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown', 'mkd']



# ---------------------
# LATEX
# ---------------------
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add = '''
" latex 
let g:latex_latexmk_options = '-pdf'
let g:vimtex_view_general_viewer = '/usr/bin/evince'
let g:vimtex_view_general_options = '@line @pdf @tex'
let g:vimtex_compiler_latexmk = {
	\ 'background': 1,
	\ 'build_dir': '',
	\ 'continuous': 1,
	\ 'options': [
	\    '-pdfdvi', 
	\    '-verbose',
	\    '-file-line-error',
	\    '-synctex=1',
	\    '-interaction=nonstopmode',
	\],
\}
'''


[[plugins]]
repo = 'PietroPate/vim-tex-conceal'
on_ft = ['tex']
hook_add = '''
set conceallevel=0
let g:tex_conceal="adgmb"
'''

[[plugins]]
repo = 'gauteh/vim-evince-synctex'
of_ft = ['tex']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# html/css
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [ 'html', "css" ]

[[plugins]]
repo = 'gorodinskiy/vim-coloresque'
on_ft = [ 'html', "css" ]

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = [ 'css', 'html' ]

# javascript
[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'


[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['html', 'xhtml', 'javascript', 'typescript', 'javascript.jsx', 'typescript.tsx']
hook_add = '''
  let g:closetag_filenames='*.html'
  let g:closetag_xhtml_filenames='*.jsx,*.tsx,*.vue'
  let g:closetag_filetypes='html'
  let g:closetag_xhtml_filetypes='jsx,tsx,javascript.jsx,typescript.tsx,vue'
  let g:closetag_emptyTags_caseSensitive=1
  let g:closetag_shortcut='>'
'''
